// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdFHPhXzZGrJCxcw2Db-ne4GPUsTzvD_Q',
    appId: '1:470717283669:web:006fd28fecdd123d7ac3dc',
    messagingSenderId: '470717283669',
    projectId: 'procs-app',
    authDomain: 'procs-app.firebaseapp.com',
    storageBucket: 'procs-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcj2Wgd_NZg7JcTDnLye7dzM6W7sOdAbk',
    appId: '1:470717283669:android:e2aef77f0c9811297ac3dc',
    messagingSenderId: '470717283669',
    projectId: 'procs-app',
    storageBucket: 'procs-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAylcJf_DaKGaBlInlmlR_ZzRHhiiMJ-m4',
    appId: '1:470717283669:ios:c58e97b94c5689837ac3dc',
    messagingSenderId: '470717283669',
    projectId: 'procs-app',
    storageBucket: 'procs-app.firebasestorage.app',
    iosBundleId: 'com.example.procsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAylcJf_DaKGaBlInlmlR_ZzRHhiiMJ-m4',
    appId: '1:470717283669:ios:c58e97b94c5689837ac3dc',
    messagingSenderId: '470717283669',
    projectId: 'procs-app',
    storageBucket: 'procs-app.firebasestorage.app',
    iosBundleId: 'com.example.procsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdFHPhXzZGrJCxcw2Db-ne4GPUsTzvD_Q',
    appId: '1:470717283669:web:d9e29ad63a9fc6847ac3dc',
    messagingSenderId: '470717283669',
    projectId: 'procs-app',
    authDomain: 'procs-app.firebaseapp.com',
    storageBucket: 'procs-app.firebasestorage.app',
  );
}
